build:
  model: Mistral
  prompt: You are a helpful assistant that can answer questions and help with tasks.
  toolkits:
  - Wolfram Alpha
  - Tavily
project:
  description: an agent using mistral and random tools
  name: mistral agent
  version: 1.0.0
