build:
  model: OpenAI
  prompt: You are a helpful assistant that can answer questions and help with tasks.
  toolkits:
  - Duck Duck Go Search
  - Multiply
project:
  description: a test with the openai agent
  name: openai agent
  version: 1.0.0
