build:
  model: Meta Llama
  prompt: You are a helpful assistant that can answer questions and help with tasks.
  toolkits:
  - Multiply
  - Duck Duck Go Search
  - Wikipedia Search
project:
  description: a random test agent
  name: agent
  version: 1.0.0
