build:
  model: Meta Llama
  prompt: You are a helpful assistant that can answer questions and help with tasks.
  toolkits:
  - Duck Duck Go Search
  - Multiply
project:
  description: an agent with access to custom math tool and duck duck go
  name: Math Tutor
  version: 1.0.0
