build:
  model: OpenAI
  prompt: You are a helpful assistant that can answer questions and help with tasks.
  toolkits:
  - Stack Exchange
  - Replit Code Interpreter
  - Duck Duck Go Search
project:
  description: a test agent
  name: test agent
  version: 1.0.0
