build:
  model: Meta Llama
  prompt: You are a helpful assistant that can answer questions and help with tasks.
  toolkits:
  - Duck Duck Go Search
project:
  description: a test agent
  name: agent
  version: 1.0.0
